version: v1.2.0

dsn: memory # Overwritten by ENV variable in docker-compose

serve:
  public:
    base_url: http://localhost:4455/auth/
    cors:
      enabled: false
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://localhost:3000/
  allowed_return_urls:
    - http://localhost:3000

  methods:
    password:
      enabled: true
  
  flows:
    error:
      ui_url: http://localhost:3000/auth/error
    settings:
      ui_url: http://localhost:3000/auth/settings
      privileged_session_max_age: 15m
    recovery:
      enabled: true
      ui_url: http://localhost:3000/auth/recovery
    verification:
      enabled: true
      ui_url: http://localhost:3000/auth/verification
      after:
        default_browser_return_url: http://localhost:3000/
    logout:
      after:
        default_browser_return_url: http://localhost:3000/auth/login
    login:
      ui_url: http://localhost:3000/auth/login
      lifespan: 10m
    registration:
      lifespan: 10m
      ui_url: http://localhost:3000/auth/register
      after:
        password:
          hooks:
            - hook: session

log:
  level: info

secrets:
  cookie:
    - bd9558dc3af268cb914679fb2cf7e26f67604773fde6b1442ccbd8813c13963e
  cipher:
    - bd9558dc3af268cb914679fb2cf7e26f

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true