- id: "api-access"
  upstream:
    preserve_host: false
    url: "http://backend:3000"
  match:
    url: "http://<.*>:4456/<.*>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: header
