name: Test Build Containers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [management, redirect, analytics, web-ui, security]
        include:
          - service: management
            context: ./services/management
          - service: redirect
            context: ./services/redirect
          - service: analytics
            context: .
            file: ./services/analytics/Dockerfile
          - service: web-ui
            context: ./web-ui
          - service: security
            context: ./services/security

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prune Docker system
        run: docker system prune -af

      - name: Build Docker image (Test Only)
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=min
